language: python
python:
  - "3.7-dev"
install:
  - pip install pytest-cov
  - pip install pytest-xdist
  - pip install codacy-coverage
script:
  - export CODACY_PROJECT_TOKEN=62f659419ef84f4cb09a104902e40664
  - pytest --cov-report xml
  - python-codacy-coverage -r coverage.xml